language: java
jdk:
  - oraclejdk11

addons:
  sonarcloud:
    organization: "artemas-muzanenhamo-github"
    token:
      secure: "A8ML3Ixia7Seh8UXwJG7+unTX643coUHtkyML+0cbqfMNYtJrenpkqrV718SyXw1K+tPIAMZtQmgUS/kQ/xHKBha0/5/EBPLMDQKmMYrFYbo5rhIblz0SPotJsVTP8HFRUFTOD8ychjI0H2h0W9s8oqZUgdE/fVfkAO14lDZrXGpLGmuoP7Zwi/NYO4W1dDpXMv9kwhchEqynIR4ObXDAFuMEX1YXByJIQuHl3mgM9a8ab5hKoB+r0zosbr4Y2eyQmoy27kDZIcrRP1rtDVDTxvxj58ydf/PxxsUxTTUYRq++UejqLstIxTdkftP4yJFpMNmR59hGs59eJn5P1NwpffIfyUmHBXgpadotxQIZ+LO0vxAPsYmqMo5EpE7ZI9TxqO+GGtXWbJX5ExwbOeQ+v8e81pyHUdK+9ZFek/buTBEGlE57XqUI+PexX0RQwN+UNPwsjDu6MfyOHHoFb1ZHleY22v5nKTzwSQS7Qsz1NLdKg5e5y/SLabZQhxRanikL0RFMCwiQA9JtXNLzpX5V/+k8UTzAzZi3aJgm6ChWte+bNybfK5kF0R8p4ML/WY1NE7dL6yythVsP3FIu2NvAtMsGMRITARI4B5DtM6zjYrpRZmaQgdNn6erX7EE684T7zNM/5qzEG5/OlH73i9a8zaXv3MhJH6YzgN6SF55yXI="

script:
  - ./gradlew build
  - ./gradlew sonarqube