version: '3.7'
services:
  configuration-server:
    build: ./configuration-server
    container_name: configuration-server
    ports:
      - "8888:8888"
  discovery-server:
    build: ./discovery-server
    container_name: discovery-server
    ports:
      - "8761:8761"
  gateway:
    depends_on:
      - configuration-server
    build: ./gateway
    container_name: gateway
    ports:
      - "9999:9999"
  identity-service:
    build: ./identity-service
    container_name: identity-service
    ports:
      - "8080:8080"
  license-service:
    build: ./license-service
    container_name: license-service
    ports:
      - "8081:8081"
