services:
  configuration-server:
    build: ./configuration-server
    container_name: configuration-server
    ports:
      - "8888:8888"
    restart: always
  discovery-server:
    build: ./discovery-server
    container_name: discovery-server
    ports:
      - "8761:8761"
    restart: always
  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "9999:9999"
    restart: always
    depends_on:
      - configuration-server
  identity-service:
    build: ./identity-service
    container_name: identity-service
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - configuration-server
      - gateway
      - discovery-server
    environment:
      SPRING_DATA_MONGODB_HOST: host.docker.internal
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_DATABASE: identity-service-db
    extra_hosts:
      - "host.docker.internal:host-gateway"
  license-service:
    build: ./license-service
    container_name: license-service
    ports:
      - "8081:8081"
    restart: always
    depends_on:
      - configuration-server
      - gateway
      - discovery-server
    environment:
      SPRING_DATA_MONGODB_HOST: host.docker.internal
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_DATABASE: license-service-db
    extra_hosts:
      - "host.docker.internal:host-gateway"
  health-service:
    build: ./health-service
    container_name: health-service
    ports:
      - "8082:8082"
    restart: always
    depends_on:
      - configuration-server
      - gateway
      - discovery-server
    environment:
      SPRING_DATA_MONGODB_HOST: host.docker.internal
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_DATABASE: health-service-db
    extra_hosts:
      - "host.docker.internal:host-gateway"
# TODO: Get containers to build sequentially.

volumes:
  mongo-data:

