codecov:
  token: 5b228940-1dd2-4052-b285-0e2a82ed530b

coverage:
  notify:
    slack:
      default:
        url: "https://hooks.slack.com/services/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"
        threshold: 1%
        only_pulls: false
        branches: null
        flags: null
        paths: null
