spring:
  main:
    banner-mode: console
  banner:
    location: classpath:banner.txt
    charset: utf-8

---

spring:
  application:
    name: configuration-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
        default-profile: dev
server:
  port: 8888

---

server:
  port: 8888
spring:
  profiles: remote
  cloud:
    config:
      server:
        git:
          uri: https://ArtemasMuzanenhamo@bitbucket.org/ArtemasMuzanenhamo/gov-poc-config-server.git
