spring:
  application:
    name: configuration-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
#          TODO: Make Spring Cloud use DEV Profile in order to find the right dev config in classpath:/shared
#          TODO: http://localhost:8888/gateway/default
#        default-profile:
server:
  port: 8888

---

server:
  port: 8888
spring:
  profiles: remote
  cloud:
    config:
      server:
        git:
          uri: https://ArtemasMuzanenhamo@bitbucket.org/ArtemasMuzanenhamo/gov-poc-config-server.git
