# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1

orbs:
  gradle: circleci/gradle@3.0.0

jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0.2
    steps:
      - checkout
      - run: java --version

workflows:
    example-workflow:
      jobs:
        - gradle/test