# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1

orbs:
  gradle: circleci/gradle@3.0.0

workflows:
    example-workflow:
      jobs:
        - gradle/test:
            executor: cimg/openjdk:11.0 