server:
  port: 8082
spring:
  application:
    name: health-service
  cloud:
    config:
      uri: http://localhost:8888
  mongodb:
    embedded:
      version: 3.2.2
  data:
    mongodb:
      database: patient-service
      host: localhost
      port: 27017
    rest:
      base-path: /search-id
