server:
  port: 8082
spring:
  profiles:
    application:
      name: health-service
    active:
      - docker
#  TODO: We need to user cloud config. Check Identity-Service
  config:
    location: http://configuration-server:8888

---

spring:
  profiles: dev
  application:
    name: health-service
  config:
    location: http://localhost:8888