spring:
  main:
    banner-mode: console
  banner:
    location: classpath:banner.txt
    charset: utf-8

---

spring:
  profiles:
    active:
      - docker
server:
  port: 9999
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka

---

spring:
  profiles: dev
server:
  port: 9999
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
