spring:
  data:
      mongodb:
        host: localhost
        port: 27017
        database: identity-service-db
server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka