spring:
  main:
    banner-mode: console
  banner:
    location: classpath:banner.txt
    charset: utf-8

---

spring:
  profiles:
    active:
      - docker
  data:
    mongodb:
      host: mongo-db-service
      port: 27017
      database: license-service-db
server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka

---

spring:
  profiles: dev
  data:
    mongodb:
      host: localhost
      port: 27017
      database: license-service-db
server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
