spring:
  profiles: prod
  data:
    mongodb:
      host: localhost
      port: 27017
      database: license-service-db
  application:
    name: license-service
server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka