spring:
  application:
    name: discovery-server
eureka:
  dashboard:
    enabled: true
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    appname: discovery-server
server:
  port: 8761
